### PR TITLE
Fixed bug with checkmark clean up while adding new peers in list

### PR DESCRIPTION
**Pull request by vikulin**
1. Fixed bug with checkmark clean up while adding new peers in list
2. Moved to pure threading instead of coroutines

### CODE REVIEW

**Comment by 6543** [comment]
@ChronosX88 any update?

**Comment by 6543** [comment]
@vikulin any update?

**Comment by ChronosXYZ** [comment]
> @vikulin any update?

@6543 Idk why this PR is hanging, I will ask @vikulin.

**Comment by vikulin** [comment]
v 1.5 new release has been published

1. Fixed yggdrasil-network#19 issue (app crash after networks switch).
2. Upgrade yggdrasil core to 0.3.15
3. Added About app screen

**Pull request merged**
