### PR TITLE
README.md changes

### PR DESCRIPTION
**Pull request by Nickoriginal**
This pull request:
1. Replaces three screenshots in the README.md from the random Github user content address with the three screenshots directly from the repository.
2. Adds new one (last) screenshot with new Firefox Proton redesign (89+).
3. Contains small improvements to the text.

### CODE REVIEW

**Comment by 6543** [comment]
just some thought on the png's - are they optimized?

-> https://tinypng.com/
-> [optipng](https://archlinux.org/packages/community/x86_64/optipng/)
...

**Comment by Nickoriginal** [comment]
First three screenshots are same as [here](https://github.com/yggdrasil-network/crispa-android/blob/master/README.md) (just downloaded and copied).

**Comment by Nickoriginal** [comment]
Here is my fourth screenshot after tinypng
yggdrasilscreenshot4(1)

**Comment by Nickoriginal** [comment]
Should I replace [previous](https://github.com/Nickoriginal/crispa-android/blob/master/yggdrasilscreenshot4.png?raw=true)?

**Comment by 6543** [comment]
I'm not a maintainer of this project- you have to ask them ;)

**Review by ChronosXYZ — CHANGES_REQUESTED** [review]
Move images into new folder.

**Comment by Nickoriginal** [comment]
Done now.

**Review by Nickoriginal — COMMENTED** [review]
All is OK: files moved to new folder "yggdrasilscreenshots", will be automatically synced with repo and README.md after merging.

**Review by ChronosXYZ — CHANGES_REQUESTED** [review]
Move to folder named "docs" pls.

**Comment by Nickoriginal** [comment]
Done.

**Comment by Nickoriginal** [comment]
@ChronosX88 files moved.

**Comment by ChronosXYZ** [comment]
@Nickoriginal Next time please squash your commits, there are too many of them.

**Pull request merged**
